name: busao_do_role
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  http: ^1.2.1
  file_picker: ^11.0.2
  dio: ^5.4.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Configuração de Assets
  assets:
    - assets/img/logo_branca.png
    - assets/img/logo_preta.png

  # Configuração das Fontes (Nome simplificado sem espaços para evitar bugs na Web)
  fonts:
    - family: TitanOne
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf

# Configuração automática dos ícones do "Busão do Rolê"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon_source.png"
  web:
    generate: true
    image_path: "app_icon_source.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
