pubspec.yaml:
name: busao_do_role
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  http: ^1.2.1
  file_picker: ^8.0.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Configuração de Assets (Imagens, etc)
  assets:
    - assets/img/logo_branca.png
    - assets/img/logo_preta.png

  # Caso queira adicionar a fonte Inter no futuro:
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700